# Generated by Django 4.0.5 on 2022-06-06 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=200)),
                ('제목', models.CharField(max_length=200, null=True)),
                ('학명', models.CharField(max_length=200, null=True)),
                ('문', models.CharField(max_length=200, null=True)),
                ('강', models.CharField(max_length=200, null=True)),
                ('목', models.CharField(max_length=200, null=True)),
                ('원산지', models.CharField(max_length=200, null=True)),
                ('분포지', models.CharField(max_length=200, null=True)),
                ('서식지', models.CharField(max_length=200, null=True)),
                ('크기', models.CharField(max_length=200, null=True)),
                ('꽃의색깔', models.CharField(max_length=200, null=True)),
                ('개화시기', models.CharField(max_length=200, null=True)),
                ('생활형', models.CharField(max_length=200, null=True)),
                ('설명', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plant.plant')),
            ],
        ),
    ]
